### ISSUE TITLE
MAML Model Support

### ISSUE THREAD

**Issue by turtleman99** [NVlabs/Bongard-LOGO#10]
Hi,

Thank you for your excellent work! In the formal print, I found that MAML results were not reported. But did exist MAML code and related scripts under the `Bongard-LOGO_Baselines/`.

I tried to run those scripts but got an error shown as below. 

```sh
File "*/Bongard-LOGO_Baselines/models/maml.py", line 145, in forward
    return F.linear(input, params['weight'], bias)
KeyError: 'weight'
```
The `params` is an empty `orderedDict` as I print it out. I used both `run_maml_model.sh` and `run_maml_v2_model.sh` to train the model, but got the same error. Is there anything I can do to fix it?

Thank you for any help.

**Comment by weilinie** [comment]
Hi @turtleman99, thanks for your interest in our work. Initially, we tried the MAML implementation (method='maml' [here](https://github.com/NVlabs/Bongard-LOGO/blob/b3669f5a06695106ea508726da507c4722cc0c00/Bongard-LOGO_Baselines/models/maml.py#L164)) but had the memory issue. So in the later experiments, we only used the ANIL version (method='anil').

**Comment by turtleman99** [comment]
Gotcha. Thank you for your information!
