### ISSUE TITLE
run_moco_model.sh results in "KeyError: 'moco'"

### ISSUE THREAD

**Issue by simitii** [NVlabs/Bongard-LOGO#6]
When I run the "run_moco_model.sh" script. It results in the following error. It seems like "moco" model does not exist in the models directory. How can we fix this?

> Traceback (most recent call last):
  File "train_moco.py", line 300, in <module>
    main(config)
  File "train_moco.py", line 120, in main
    model = models.make(config['model'], **config['model_args'])
  File "/content/Bongard-LOGO/Bongard-LOGO_Baselines/models/models.py", line 20, in make
    model = models[name](**kwargs)
KeyError: 'moco'

**Comment by weilinie** [comment]
Hi @simitii, thanks for pointing out this issue. I just added the moco model defined [here](https://github.com/NVlabs/Bongard-LOGO/blob/master/Bongard-LOGO_Baselines/models/classifier.py), and now the issue should be fixed.

**Comment by weilinie** [comment]
Closing it. Feel free to reopen if you have further questions.
