### ISSUE TITLE
Creating Bongard Logo dataset

### ISSUE THREAD

**Issue by prateekgulati** [NVlabs/Bongard-LOGO#7]
python run.py throws an error when trying to run from Bongard-LOGO/examples/02-bongard_logo/

This happens 'cuz the bongard module is not accessible from this folder. 
I fixed it by moving the 'bongard' folder to Bongard-LOGO/examples/02-bongard_logo/ but this might not be the best solution.
There might be a need to arrange the directories.

**Comment by weilinie** [comment]
We actually expect the users to first install the `bongard` library as instructed [here](https://github.com/NVlabs/Bongard-LOGO#installation) before running the data generation code.

**Comment by weilinie** [comment]
Closing it. Feel free to reopen if you have further questions.
